package com.example.courselistapp.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme
val md_theme_light_primary = Color(0xFF006A6A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6FF7F7)
val md_theme_light_onPrimaryContainer = Color(0xFF002020)
val md_theme_light_secondary = Color(0xFF006A69)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF6FF7F6)
val md_theme_light_onSecondaryContainer = Color(0xFF002020)
val md_theme_light_tertiary = Color(0xFF006874)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF4FBFB)
val md_theme_light_onBackground = Color(0xFF161D1D)
val md_theme_light_surface = Color(0xFFF4FBFB)
val md_theme_light_onSurface = Color(0xFF161D1D)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E5)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4949)
val md_theme_light_surfaceContainer = Color(0xFFEFF6F6)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)

// Dark Theme
val md_theme_dark_primary = Color(0xFF4CD9D9)
val md_theme_dark_onPrimary = Color(0xFF003737)
val md_theme_dark_primaryContainer = Color(0xFF004F4F)
val md_theme_dark_onPrimaryContainer = Color(0xFF6FF7F7)
val md_theme_dark_secondary = Color(0xFF4CDAD9)
val md_theme_dark_onSecondary = Color(0xFF003737)
val md_theme_dark_secondaryContainer = Color(0xFF004F4F)
val md_theme_dark_onSecondaryContainer = Color(0xFF6FF7F6)
val md_theme_dark_tertiary = Color(0xFF4FD8E8)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_background = Color(0xFF161D1D)
val md_theme_dark_onBackground = Color(0xFFDBE4E4)
val md_theme_dark_surface = Color(0xFF161D1D)
val md_theme_dark_onSurface = Color(0xFFDBE4E4)
val md_theme_dark_surfaceVariant = Color(0xFF3F4949)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C9)
val md_theme_dark_surfaceContainer = Color(0xFF1E3434)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)